@echo off
echo Restarting ClientHub Backend Server...
echo.
echo Step 1: Stopping any running Node processes on port 5000...
for /f "tokens=5" %%a in ('netstat -aon ^| find ":5000" ^| find "LISTENING"') do taskkill /F /PID %%a 2>nul
timeout /t 2 /nobreak >nul
echo.
echo Step 2: Starting server...
npm start
